### ISSUE TITLE
[Feature]: Changing system to one topic

### ISSUE THREAD

**Issue by bafaurazan** [knmlprz/TrailblazerML#132]
### Feature Context

code idea to change from:

```
controller_manager:
  ros__parameters:
    update_rate: 30
    controllers:
      - diff_drive_controller_left
      - diff_drive_controller_right
      - joint_broad
    diff_drive_controller_left:
      type: diff_drive_controller/DiffDriveController
    diff_drive_controller_right:
      type: diff_drive_controller/DiffDriveController
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller_left:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['left_wheel_front_joint']
    right_wheel_names: ['left_wheel_back_joint']
    wheel_separation: 1.17
    wheel_radius: 0.13
    use_stamped_vel: false

diff_drive_controller_right:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['right_wheel_front_joint']
    right_wheel_names: ['right_wheel_back_joint']
    wheel_separation: 1.17
    wheel_radius: 0.13
    use_stamped_vel: false

```
to
```
controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['base_link_left_wheel_frontside', 'base_link_left_wheel_backside']
    right_wheel_names: ['base_link_right_wheel_frontside', 'base_link_right_wheel_backside']
    wheel_separation: 0.4
    wheel_radius: 0.05

    use_stamped_vel: false

# joint_broad:
#   ros__parameters:

```

### Acceptance Criteria

- [ ] System is working on one topic not two

#### controlling gazebo articubot_one
- https://github.com/joshnewans/articubot_one/blob/main/description/ros2_control.xacro
- https://github.com/joshnewans/articubot_one/blob/main/launch/launch_sim.launch.py
- https://github.com/joshnewans/articubot_one/blob/main/config/my_controllers.yaml
#### serial_motor_demo
- https://github.com/joshnewans/serial_motor_demo/blob/main/serial_motor_demo_msgs/msg/MotorCommand.msg
- https://github.com/joshnewans/serial_motor_demo/blob/main/serial_motor_demo/serial_motor_demo/driver.py
#### serial
- https://github.com/joshnewans/serial/tree/newans_ros2
#### ros_arduino_bridge 
- https://github.com/joshnewans/ros_arduino_bridge/blob/main/ROSArduinoBridge/ROSArduinoBridge.ino 
  - ten kod zmienia twist na dwa lineary
- https://github.com/joshnewans/ros_arduino_bridge/blob/main/ROSArduinoBridge/diff_controller.h 
  - ten kod dostosowuje prędkość kół na podstawie odometrii
#### system gazebo dla 4 kół
- https://robotics.snowcron.com/robotics_ros2/diff_drive_libgazebo_4_wheels.htm
#### diffdrive_arduino
- https://github.com/joshnewans/diffdrive_arduino/blob/main/include/diffdrive_arduino/config.h
  - oprogramowanie do konfiguracji kontrolera na robocie
